using System ;
using System.Collections ;
using System.Collections.ObjectModel ;
using System.Windows ;
using System.Windows.Controls ;
using KayMcCormick.Dev ;
using Application = System.Windows.Application ;

namespace KayMcCormick.Lib.Wpf
{
    /// <summary>
    /// Control for displaying all known resources to the application.
    /// </summary>
    [ TitleMetadataAttribute("Resources Explorer") ]
    public partial class AllResourcesTree : UserControl , IView1, IView<AllResourcesTreeViewModel>
    {
        private string _viewTitle = "Resources Explorer" ;
        private AllResourcesTreeViewModel _viewModel ;

        /// <summary>Parameterless constructor.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        //public AllResourcesTree() { InitializeComponent(); }
        public AllResourcesTree(AllResourcesTreeViewModel viewModel)
        {
            _viewModel = viewModel ;
            InitializeComponent();
        }

        #region Implementation of IView1
        public string ViewTitle { get => _viewTitle ; set => _viewTitle = value ; }
        #endregion

        #region Implementation of IView<out AllResourcesTreeViewModel>
        public AllResourcesTreeViewModel ViewModel { get => _viewModel ; set => _viewModel = value ; }
        #endregion
    }

    public class AllResourcesTreeViewModel
    {
        private ObservableCollection<ResourceNodeInfo> _allResourcesCollection =
            new ObservableCollection<ResourceNodeInfo>();

        private ResourceNodeInfo _appNode;

        public AllResourcesTreeViewModel ( ) {
                PopulateResourcesTree();

        }
        private void PopulateResourcesTree()
        {
            try
            {
                var current = (BaseApp)Application.Current;
                _appNode = new ResourceNodeInfo { Key = "Application", Data = current };
                var appResources = new ResourceNodeInfo
                                   {
                                       Key  = "Resources",
                                       Data = current.Resources
                                   };
                _appNode.Children.Add(appResources);
                AddResourceNodeInfos(appResources);
                AllResourcesCollection.Add(_appNode);
                foreach ( Window currentWindow in current.Windows )
                {
                    HandleWindow(currentWindow);
                }
            }
#pragma warning disable CS0168 // The variable 'ex' is declared but never used
            catch (Exception ex)
#pragma warning restore CS0168 // The variable 'ex' is declared but never used
            {
            }
        }
        public ObservableCollection<ResourceNodeInfo> AllResourcesCollection
            => _allResourcesCollection;

        private void AddResourceNodeInfos(ResourceNodeInfo appResources)
        {
            var res = (ResourceDictionary)appResources.Data;
            appResources.SourceUri = res.Source;

            foreach (var md in res.MergedDictionaries)
            {
                var mdr = new ResourceNodeInfo { Key = md.Source, Data = md };
                AddResourceNodeInfos(mdr);
                appResources.Children.Add(mdr);
            }

            foreach (DictionaryEntry haveResourcesResource in res)
            {
                if (haveResourcesResource.Key      != null
                    && haveResourcesResource.Value != null)
                {
                    var resourceInfo = new ResourceNodeInfo
                                       {
                                           Key = haveResourcesResource.Key
                                          ,
                                           Data = haveResourcesResource.Value
                                       };
                    appResources.Children.Add(resourceInfo);
                }
            }
        }

        private void HandleWindow(Window w)
        {
            var winNode = new ResourceNodeInfo
                          {
                              Key  = w.GetType(),
                              Data = new ControlWrap<Window>(w)
                          };
            _appNode.Children.Add(winNode);
            var winRes = new ResourceNodeInfo { Key = "Resources", Data = w.Resources };
            winNode.Children.Add(winRes);
            AddResourceNodeInfos(winRes);
        }
    }
}