using System.Windows.Controls ;
using KayMcCormick.Dev ;

namespace KayMcCormick.Lib.Wpf
{
    /// <summary>
    /// Control for displaying all known resources to the application.
    /// </summary>
    [ TitleMetadataAttribute("Resources Explorer") ]
    public partial class AllResourcesTree : UserControl , IView1, IView<AllResourcesTreeViewModel>
    {
        private string _viewTitle = "Resources Explorer" ;
        private AllResourcesTreeViewModel _viewModel ;

        /// <summary>Parameterless constructor.</summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        //public AllResourcesTree() { InitializeComponent(); }
        public AllResourcesTree(AllResourcesTreeViewModel viewModel)
        {
            _viewModel = viewModel ;
            InitializeComponent();
        }

        #region Implementation of IView1
        public string ViewTitle { get => _viewTitle ; set => _viewTitle = value ; }
        #endregion

        #region Implementation of IView<out AllResourcesTreeViewModel>
        public AllResourcesTreeViewModel ViewModel { get => _viewModel ; set => _viewModel = value ; }
        #endregion
    }
}