using System.Windows.Controls ;

namespace KayMcCormick.Lib.Wpf
{
    /// <summary>
    ///     Interaction logic for TypeControl2.xaml
    /// </summary>
    public sealed partial class TypeControl2 : UserControl
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="TypeControl2" />
        ///     class.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public TypeControl2 ( ) { InitializeComponent ( ) ; }
    }
}