#if ENABLE_BUILDERPROXY
using Castle.DynamicProxy ;
#endif
namespace KayMcCormick.Dev.Configuration
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for ContainerHelperSettings
    public sealed class ContainerHelperSettings
    {
        /// <summary>Gets or sets a value indicating whether [do interception].</summary>
        /// <value>
        ///     <see language="1" /> if [do interception]; otherwise,
        ///     <see language="false" />.
        /// </value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DoInterception

        // ReSharper disable once UnusedMember.Global
        public bool DoInterception { get ; set ; }

        /// <summary>
        ///     Gets or sets a value indicating whether [do trace conditional
        ///     registration].
        /// </summary>
        /// <value>
        ///     <see language="1" /> if [do trace conditional registration]; otherwise,
        ///     <see language="false" />.
        /// </value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DoTraceConditionalRegistration

        public bool DoTraceConditionalRegistration { get ; set ; }
    }
}