// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2008:Do not create tasks without passing a TaskScheduler", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.Pipeline.Continuation(System.Threading.Tasks.Dataflow.IDataflowBlock,System.String)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1823:Unused field '_getResource'.", Justification = "<Pending>", Scope = "member", Target = "~F:ProjLib.LogInvocationSpan._getResource")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1823:Unused field 'Logger'.", Justification = "<Pending>", Scope = "member", Target = "~F:ProjLib.ProjLibContainer.Logger")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1823:Unused field 'Logger'.", Justification = "<Pending>", Scope = "member", Target = "~F:ProjLib.VersionControl.Logger")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'DateTime.Parse(string)' could vary based on the current user's locale settings. Replace this call in 'EventTimeConverter.Read(ref Utf8JsonReader, Type, JsonSerializerOptions)' with a call to 'DateTime.Parse(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.EventTimeConverter.Read(System.Text.Json.Utf8JsonReader@,System.Type,System.Text.Json.JsonSerializerOptions)~System.DateTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'void EventTimeConverter.Write(Utf8JsonWriter writer, DateTime value, JsonSerializerOptions options)', validate parameter 'writer' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.EventTimeConverter.Write(System.Text.Json.Utf8JsonWriter,System.DateTime,System.Text.Json.JsonSerializerOptions)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'Logger.Info(string, string)' could vary based on the current user's locale settings. Replace this call in 'LogInvocationSpan.LogInvocationSpan(TextSpan, ILogInvocation)' with a call to 'Logger.Info(IFormatProvider, string, string)'.", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.LogInvocationSpan.#ctor(Microsoft.CodeAnalysis.Text.TextSpan,AnalysisFramework.ILogInvocation)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'char.ToString()' could vary based on the current user's locale settings. Replace this call in 'MruItem.MruItem(string, string)' with a call to 'char.ToString(IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.MruItem.#ctor(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'Logger.Trace(string, string)' could vary based on the current user's locale settings. Replace this call in 'ProjLibModule.Load(ContainerBuilder)' with a call to 'Logger.Trace(IFormatProvider, string, string)'.", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.ProjLibModule.Load(Autofac.ContainerBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.VersionControl.CloneProjectAsync(ProjLib.AnalysisRequest)~System.Threading.Tasks.Task{ProjLib.AnalysisRequest}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'DefaultVisit' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.Visitor2.DefaultVisit(Microsoft.CodeAnalysis.SyntaxNode)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.Visitor4.DefaultVisitAsync(Microsoft.CodeAnalysis.SyntaxNode)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'Logger.Trace(string, int)' could vary based on the current user's locale settings. Replace this call in 'Visitor4.RecordLocation(Location, out bool)' with a call to 'Logger.Trace(IFormatProvider, string, int)'.", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.Visitor4.RecordLocation(Microsoft.CodeAnalysis.Location,System.Boolean@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'Logger.Info(string, bool)' could vary based on the current user's locale settings. Replace this call in 'Workspaces.MakeWorkspaceAsync(AnalysisRequest)' with a call to 'Logger.Info(IFormatProvider, string, bool)'.", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.Workspaces.MakeWorkspaceAsync(ProjLib.AnalysisRequest)~System.Threading.Tasks.Task{Microsoft.CodeAnalysis.Workspace}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'MakeWorkspaceAsync' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.Workspaces.MakeWorkspaceAsync(ProjLib.AnalysisRequest)~System.Threading.Tasks.Task{Microsoft.CodeAnalysis.Workspace}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.WorkspacesViewModel.AnalyzeCommand(System.Object)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'NewMethod' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:ProjLib.WorkspacesViewModel.NewMethod(System.Threading.Tasks.Dataflow.ActionBlock{AnalysisFramework.ILogInvocation})~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'SolutionsFilesList' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:ProjLib.BuildResults.SolutionsFilesList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'Spans' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:ProjLib.ISpanToolTipViewModel.Spans")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'Properties' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:ProjLib.IVsInstance.Properties")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'Properties' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:ProjLib.LogEventInstance.Properties")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1710:Rename ProjLib.ActiveSpans to end in 'Dictionary'.", Justification = "<Pending>", Scope = "type", Target = "~T:ProjLib.ActiveSpans")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1040:Avoid empty interfaces", Justification = "<Pending>", Scope = "type", Target = "~T:ProjLib.IViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1812:PipelineRemoteSource is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "<Pending>", Scope = "type", Target = "~T:ProjLib.PipelineRemoteSource")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name ProjLib.Properties.AssertionConditionType.IS_FALSE.", Justification = "<Pending>", Scope = "type", Target = "~T:ProjLib.Properties.AssertionConditionType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1714:Flags enums should have plural names", Justification = "<Pending>", Scope = "type", Target = "~T:ProjLib.Properties.CollectionAccessType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1812:SpanToolTipViewModel is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "<Pending>", Scope = "type", Target = "~T:ProjLib.SpanToolTipViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1064:Exceptions should be public", Justification = "<Pending>", Scope = "type", Target = "~T:ProjLib.UnableToInitializeWorkspace")]