//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjLib.LibResources", typeof(LibResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Windows ;
        ///using System.Windows.Data ;
        ///
        ///namespace WpfApp2
        ///{
        ///    public static class AttachedProps
        ///    {
        ///        
        ///        public static readonly DependencyProperty PropertiesCollectionProperty =
        ///            DependencyProperty.RegisterAttached (
        ///                                                 &quot;PropertiesCollection&quot;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AttachedProps {
            get {
                return ResourceManager.GetString("AttachedProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using NLog ;
        ///
        ///namespace LogTest
        ///{
        ///    class Program
        ///    {
        ///        private static readonly  Logger Logger = LogManager.GetCurrentClassLogger();
        ///        static void Main(string[] args) {
        ///            Action&lt;string&gt; xx = Logger.Info;
        ///            xx(&quot;hi&quot;);
        ///            Logger.Debug ( $&quot;Hello {1}&quot; ) ;
        ///            try {
        ///                string xxx = null;
        ///                var q = xxx.T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Program_Parse {
            get {
                return ResourceManager.GetString("Program_Parse", resourceCulture);
            }
        }
    }
}
