// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1816:Change BaseApp.Dispose() to call GC.SuppressFinalize(object). This will prevent derived types that introduce a finalizer from needing to re-implement 'IDisposable' to call it.", Justification = "<Pending>", Scope = "member", Target = "~M:KayMcCormick.Lib.Wpf.BaseApp.Dispose")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1063:Modify 'BaseApp.Dispose' so that it calls Dispose(true), then calls GC.SuppressFinalize on the current object instance ('this' or 'Me' in Visual Basic), and then returns.", Justification = "<Pending>", Scope = "member", Target = "~M:KayMcCormick.Lib.Wpf.BaseApp.Dispose")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member ErrorExit does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:KayMcCormick.Lib.Wpf.BaseApp.ErrorExit(KayMcCormick.Dev.ExitCode)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'Convert.ChangeType(object, TypeCode)' could vary based on the current user's locale settings. Replace this call in 'BaseApp.ErrorExit([ExitCode])' with a call to 'Convert.ChangeType(object, TypeCode, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:KayMcCormick.Lib.Wpf.BaseApp.ErrorExit(KayMcCormick.Dev.ExitCode)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'object ResolveExtension.ProvideValue(IServiceProvider serviceProvider)' passes a literal string as parameter 'message' of a call to 'Exception.Exception(string message)'. Retrieve the following string(s) from a resource table instead: \"No lifetime scope\".", Justification = "<Pending>", Scope = "member", Target = "~M:KayMcCormick.Lib.Wpf.ResolveExtension.ProvideValue(System.IServiceProvider)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1716:Rename namespace KayMcCormick.Lib.Wpf so that it no longer conflicts with the reserved language keyword 'Lib'. Using a reserved keyword as the name of a namespace makes it harder for consumers in other languages to use the namespace.", Justification = "<Pending>", Scope = "namespace", Target = "~N:KayMcCormick.Lib.Wpf")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1063:Provide an overridable implementation of Dispose(bool) on 'BaseApp' or mark the type as sealed. A call to Dispose(false) should only clean up native resources. A call to Dispose(true) should clean up both managed and native resources.", Justification = "<Pending>", Scope = "type", Target = "~T:KayMcCormick.Lib.Wpf.BaseApp")]