//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisAppLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalysisAppLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty code supplied.
        /// </summary>
        public static string AnalysisService_Parse_Empty_code_supplied {
            get {
                return ResourceManager.GetString("AnalysisService_Parse_Empty_code_supplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Microsoft.CodeAnalysis.CSharp&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:Microsoft.CodeAnalysis.CSharp.Binder&quot;&gt;
        ///            &lt;summary&gt;
        ///            A Binder converts names in to symbols and syntax nodes into bound trees. It is context
        ///            dependent, relative to a location in source code.
        ///            &lt;/summary&gt;
        ///            &lt;summary&gt;
        ///            This portion of the binder converts a AnonymousObjectCreationExpressionSy [rest of string was truncated]&quot;;.
        /// </summary>
        public static string doc {
            get {
                return ResourceManager.GetString("doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using NLog ;
        ///
        ///namespace LogTest
        ///{
        ///    public static class Program
        ///    {
        ///        private static readonly  Logger Logger = LogManager.GetCurrentClassLogger();
        ///        static void Main(string[] args) {
        ///            Action&lt;string&gt; xx = Logger.Info;
        ///            xx(&quot;hi&quot;);
        ///            Logger.Debug ( $&quot;Hello {1}&quot; ) ;
        ///            try {
        ///                string xxx = null;
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Program_Parse {
            get {
                return ResourceManager.GetString("Program_Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license. See the LICENSE file in the project root for more information. --&gt;
        ///
        ///&lt;!-- 
        /// To re-generate source from this file, run eng/generate-compiler-code.cmd
        ///--&gt;
        ///
        ///&lt;Tree Root=&quot;SyntaxNode&quot;&gt;
        ///  &lt;PredefinedNode Name=&quot;CSharpSyntaxNode&quot; Base=&quot;SyntaxNode&quot;/&gt;
        ///  &lt;PredefinedNode Name=&quot;SyntaxToken&quot; Base=&quot;CSharpSyntaxNode&quot;/&gt;
        ///  &lt;PredefinedNode Name=&quot;Structured [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
    }
}
