//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayMcCormick.Dev.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppInstanceInfoRequest", Namespace="http://schemas.datacontract.org/2004/07/KayMcCormick.Dev")]
    [System.SerializableAttribute()]

    public partial class AppInstanceInfoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {

            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        

        protected void RaisePropertyChanged(string propertyName) {

            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppInstanceInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/KayMcCormick.Dev")]
    [System.SerializableAttribute()]

    public partial class AppInstanceInfoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KayMcCormick.Dev.ServiceReference1.AppInstanceInfo InfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {

            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]

        public KayMcCormick.Dev.ServiceReference1.AppInstanceInfo Info {

            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        

        protected void RaisePropertyChanged(string propertyName) {

            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppInstanceInfo", Namespace="http://schemas.datacontract.org/2004/07/KayMcCormick.Dev")]
    [System.SerializableAttribute()]

    public partial class AppInstanceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KayMcCormick.Dev.ServiceReference1.WireComponentInfo[] ComponentInfosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KayMcCormick.Dev.ServiceReference1.LoggerInfo[] LoggerInfosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartupTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {

            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]

        public KayMcCormick.Dev.ServiceReference1.WireComponentInfo[] ComponentInfos {

            get {
                return this.ComponentInfosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComponentInfosField, value) != true)) {
                    this.ComponentInfosField = value;
                    this.RaisePropertyChanged("ComponentInfos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]

        public KayMcCormick.Dev.ServiceReference1.LoggerInfo[] LoggerInfos {

            get {
                return this.LoggerInfosField;
            }
            set {
                if ((object.ReferenceEquals(this.LoggerInfosField, value) != true)) {
                    this.LoggerInfosField = value;
                    this.RaisePropertyChanged("LoggerInfos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]

        public System.DateTime StartupTime {

            get {
                return this.StartupTimeField;
            }
            set {
                if ((this.StartupTimeField.Equals(value) != true)) {
                    this.StartupTimeField = value;
                    this.RaisePropertyChanged("StartupTime");
                }
            }
        }
        

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        

        protected void RaisePropertyChanged(string propertyName) {

            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WireComponentInfo", Namespace="http://schemas.datacontract.org/2004/07/KayMcCormick.Dev")]
    [System.SerializableAttribute()]

    public partial class WireComponentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KayMcCormick.Dev.ServiceReference1.WireInstanceInfo[] InstancesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {

            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]

        public System.Guid Id {

            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]

        public KayMcCormick.Dev.ServiceReference1.WireInstanceInfo[] Instances {

            get {
                return this.InstancesField;
            }
            set {
                if ((object.ReferenceEquals(this.InstancesField, value) != true)) {
                    this.InstancesField = value;
                    this.RaisePropertyChanged("Instances");
                }
            }
        }
        

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        

        protected void RaisePropertyChanged(string propertyName) {

            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoggerInfo", Namespace="http://schemas.datacontract.org/2004/07/KayMcCormick.Dev")]
    [System.SerializableAttribute()]

    public partial class LoggerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {

            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]

        public string TargetName {

            get {
                return this.TargetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetNameField, value) != true)) {
                    this.TargetNameField = value;
                    this.RaisePropertyChanged("TargetName");
                }
            }
        }
        

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        

        protected void RaisePropertyChanged(string propertyName) {

            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WireInstanceInfo", Namespace="http://schemas.datacontract.org/2004/07/KayMcCormick.Dev")]
    [System.SerializableAttribute()]

    public partial class WireInstanceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {

            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]

        public string Desc {

            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        

        protected void RaisePropertyChanged(string propertyName) {

            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAppInfoService")]

    public interface IAppInfoService {

        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppInfoService/GetAppInstanceInfo", ReplyAction="http://tempuri.org/IAppInfoService/GetAppInstanceInfoResponse")]

        KayMcCormick.Dev.ServiceReference1.AppInstanceInfoResponse GetAppInstanceInfo(KayMcCormick.Dev.ServiceReference1.AppInstanceInfoRequest request);

        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppInfoService/GetAppInstanceInfo", ReplyAction="http://tempuri.org/IAppInfoService/GetAppInstanceInfoResponse")]

        System.Threading.Tasks.Task<KayMcCormick.Dev.ServiceReference1.AppInstanceInfoResponse> GetAppInstanceInfoAsync(KayMcCormick.Dev.ServiceReference1.AppInstanceInfoRequest request);

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]

    public interface IAppInfoServiceChannel : KayMcCormick.Dev.ServiceReference1.IAppInfoService, System.ServiceModel.IClientChannel {

    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]

    public partial class AppInfoServiceClient : System.ServiceModel.ClientBase<KayMcCormick.Dev.ServiceReference1.IAppInfoService>, KayMcCormick.Dev.ServiceReference1.IAppInfoService {

        

        public AppInfoServiceClient() {

        }
        

        public AppInfoServiceClient(string endpointConfigurationName) : 

                base(endpointConfigurationName) {
        }
        

        public AppInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 

                base(endpointConfigurationName, remoteAddress) {
        }
        

        public AppInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 

                base(endpointConfigurationName, remoteAddress) {
        }
        

        public AppInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 

                base(binding, remoteAddress) {
        }
        

        public KayMcCormick.Dev.ServiceReference1.AppInstanceInfoResponse GetAppInstanceInfo(KayMcCormick.Dev.ServiceReference1.AppInstanceInfoRequest request) {

            return base.Channel.GetAppInstanceInfo(request);
        }
        

        public System.Threading.Tasks.Task<KayMcCormick.Dev.ServiceReference1.AppInstanceInfoResponse> GetAppInstanceInfoAsync(KayMcCormick.Dev.ServiceReference1.AppInstanceInfoRequest request) {

            return base.Channel.GetAppInstanceInfoAsync(request);
        }
    }
}
