using System ;
using System.Collections ;
using System.Collections.Concurrent ;
using System.Collections.Generic ;
using System.Linq ;
using System.Runtime.Serialization ;
using Autofac.Core ;
using JetBrains.Annotations ;
using KayMcCormick.Dev.Interfaces ;
using NLog ;
using NLog.Fluent ;

namespace KayMcCormick.Dev
{
    /// <summary>Default implementation for object ID provider service.</summary>
    /// <seealso cref="IObjectIdProvider" />
    internal sealed class DefaultObjectIdProvider : IObjectIdProvider
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger ( ) ;

        private readonly long _id ;

        private readonly ConcurrentDictionary < object , long > _registry ;


        // ReSharper disable once CollectionNeverUpdated.Local
        private readonly ConcurrentDictionary < long , object > _registryById ;

        /// <summary>
        ///     Initializes a new instance of the <see cref="object" />
        ///     class.
        /// </summary>
        public DefaultObjectIdProvider ( [ JetBrains.Annotations.NotNull ] ObjectIDGenerator generator )
        {
            Generator     = generator ?? throw new ArgumentNullException ( nameof ( generator ) ) ;
            _registryById = new ConcurrentDictionary < long , object > ( ) ;
            _registry     = new ConcurrentDictionary < object , long > ( ) ;
            _id           = generator.GetId ( this , out _ ) ;
        }

        private ObjectIDGenerator Generator { get ; }

        private ConcurrentDictionary < Guid , ComponentInfo > ByComponent { get ; } =
            new ConcurrentDictionary < Guid , ComponentInfo > ( ) ;

        /// <summary>Gets the instance by component registration.</summary>
        /// <param name="reg">The reg.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GetInstanceByComponentRegistration
        public IEnumerable < InstanceInfo > GetInstanceByComponentRegistration (
            [ JetBrains.Annotations.NotNull ] IComponentRegistration reg
        )
        {
            if ( reg == null )
            {
                throw new ArgumentNullException ( nameof ( reg ) ) ;
            }

            Logger.Debug (
                          $"[{_id}] {nameof ( GetInstanceByComponentRegistration )} [ {reg.DebugFormat ( )} ]:"
                         ) ;

            var regId = reg.Id ;
            var compInfo = GetComponentInfo ( regId ) ;
            return compInfo != null ? compInfo.Instances : Array.Empty < InstanceInfo > ( ) ;
        }

        /// <summary>
        /// </summary>
        /// <param name="regId"></param>
        /// <returns></returns>
        [ CanBeNull ]
        public ComponentInfo GetComponentInfo ( Guid regId )
        {
            ByComponent.TryGetValue ( regId , out var compInfo ) ;
            return compInfo ;
        }

        /// <summary>Gets the instance count.</summary>
        /// <param name="reg">The reg.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GetInstanceCount
        public int GetInstanceCount ( [ JetBrains.Annotations.NotNull ] IComponentRegistration reg )
        {
            if ( reg == null )
            {
                throw new ArgumentNullException ( nameof ( reg ) ) ;
            }

            return GetInstanceByComponentRegistration ( reg ).Count() ;
        }

        /// <summary>Gets the object instances.</summary>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GetObjectInstances
        [ JetBrains.Annotations.NotNull ]
        public IEnumerable GetObjectInstances ( ) { return _registry.Keys ; }

        /// <summary>Gets the object instance identifier.</summary>
        /// <param name="instance">The instance.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GetObjectInstanceIdentifier
        [ JetBrains.Annotations.NotNull ]
        public object GetObjectInstanceIdentifier ( [ JetBrains.Annotations.NotNull ] object instance )
        {
            var id = Generator.HasId ( instance , out _ ) ;
            return id ;
        }

        /// <summary>
        ///     <para>
        ///         Gets the object by identifier.
        ///     </para>
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        [ CanBeNull ]
        public object GetObjectById ( [ JetBrains.Annotations.NotNull ] object id )
        {
            return _registryById.TryGetValue ( ( long ) id , out var instance ) ? instance : null ;
        }

        /// <summary>
        ///     <para>
        ///         Provides the object instance identifier.
        ///     </para>
        /// </summary>
        /// <param name="instance">The instance.</param>
        /// <param name="eComponent">The e component.</param>
        /// <param name="eParameters">The e parameters.</param>
        /// <returns></returns>
        /// <exception cref="UnableToRegisterObjectIdException"></exception>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ProvideObjectInstanceIdentifier
        [ JetBrains.Annotations.NotNull ]
        public object ProvideObjectInstanceIdentifier (
            [ JetBrains.Annotations.NotNull ] object                    instance
          , [ JetBrains.Annotations.NotNull ] IComponentRegistration    eComponent
          , [ JetBrains.Annotations.NotNull ] IEnumerable < Parameter > eParameters
        )
        {
            if ( instance == null )
            {
                throw new ArgumentNullException ( nameof ( instance ) ) ;
            }

            if ( eComponent == null )
            {
                throw new ArgumentNullException ( nameof ( eComponent ) ) ;
            }

            if ( eParameters == null )
            {
                throw new ArgumentNullException ( nameof ( eParameters ) ) ;
            }

            var id = Generator.GetId ( instance , out var newFlag ) ;
            if ( ! newFlag )
            {
                return id ;
            }

            new LogBuilder ( Logger )
               .Level ( LogLevel.Debug )
               .Message ( $"Provisioned ID {id} for instance of type {instance.GetType ( )}." )
               .Property ( "objectId" ,     id )
               .Property ( "instanceType" , instance.GetType ( ).FullName )
               .Write ( ) ;
            RegisterObject ( instance , eComponent , eParameters , id ) ;

            return id ;
        }


        /// <summary>Gets the root nodes.</summary>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GetRootNodes
        [ JetBrains.Annotations.NotNull ]
        public ICollection < Guid > GetRootNodes ( ) { return ByComponent.Keys ; }

        private void RegisterObject (
            [ JetBrains.Annotations.NotNull ] object                 instance
          , [ JetBrains.Annotations.NotNull ] IComponentRegistration eComponent
          , IEnumerable < Parameter >          eParameters
          , long                               id
        )
        {
            Logger.Trace (
                          $"RegisterObject of type {instance.GetType ( )} for {eComponent.DebugFormat ( )} id is {id}"
                         ) ;
            if ( ! ByComponent.TryGetValue ( eComponent.Id , out var compReg ) )
            {
                compReg = new ComponentInfo ( ) ;
                if ( ! ByComponent.TryAdd ( eComponent.Id , compReg ) )
                {
                }
            }

            Logger.Trace ( $"Adding {instance} to reg for {eComponent.Id}" ) ;
            compReg.InstancesList.Add (
                                   new InstanceInfo
                                   {
                                       Instance = instance , Parameters = eParameters
                                   }
                                  ) ;
            if ( ! _registry.TryAdd ( instance , id ) )
            {
                throw new UnableToRegisterObjectIdException ( ) ;
            }
        }
    }
}