using Autofac;
using Autofac.Core;
using Autofac.Core.Registration;
using KayMcCormick.Dev.Interfaces;
using NLog;
using System.Linq;
using System.Runtime.Serialization;

namespace KayMcCormick.Dev
{
    /// <summary></summary>
    /// <seealso cref="Autofac.Module" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for IdGeneratorModule

}