#region header
// Kay McCormick (mccor)
// 
// FileFinder3
// WpfApp1
// IHaveLogger.cs
// 
// 2020-01-22-1:30 PM
// 
// ---
#endregion

using NLog ;

namespace KayMcCormick.Dev
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for IHaveLogger
    public interface IHaveLogger

    {
        /// <summary>Gets or sets the logger.</summary>
        /// <value>The logger.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Logger
        ILogger Logger { get ; set ; }
    }
}