#region header
// Kay McCormick (mccor)
// 
// FileFinder3
// WpfApp1
// InstanceInfo.cs
// 
// 2020-01-25-7:05 PM
// 
// ---
#endregion
using System.Collections.Generic ;
using Autofac.Core ;

namespace KayMcCormick.Dev
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for InstanceInfo
    internal sealed class InstanceInfo
    {
        /// <summary>Gets or sets the instance.</summary>
        /// <value>The instance.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Instance
        public object Instance { get ; set ; }

        /// <summary>Gets or sets the parameters.</summary>
        /// <value>The parameters.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Parameters
        public IEnumerable < Parameter > Parameters { get ; set ; }

        /// <summary>
        /// </summary>
        /// <returns></returns>
        public override string ToString ( ) { return $"InstanceInfo({Instance})" ; }
    }
}