#region header
// Kay McCormick (mccor)
// 
// KayMcCormick.Dev
// ProjLib
// IViewModel.cs
// 
// 2020-02-29-2:32 PM
// 
// ---
#endregion
namespace KayMcCormick.Dev
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for IViewModel
    public interface IViewModel
    {
    }
}