#region header
// Kay McCormick (mccor)
// 
// KayMcCormick.Dev
// ProjLib
// IViewModel.cs
// 
// 2020-02-29-2:32 PM
// 
// ---
#endregion
using KayMcCormick.Dev.Interfaces;
using System.Runtime.Serialization ;

namespace KayMcCormick.Dev
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for IViewModel
    public interface IViewModel : ISerializable, IHaveObjectId
    {
        //object TryFindResource ( object resourceKey ) ;
    }
}