#region header
// Kay McCormick (mccor)
// 
// KayMcCormick.Dev
// ProjLib
// IViewModel.cs
// 
// 2020-02-29-2:32 PM
// 
// ---
#endregion
using System ;
using System.Runtime.Serialization ;

namespace KayMcCormick.Dev
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for IViewModel
    
    public interface IViewModel : ISerializable
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="resourceKey"></param>
        /// <returns></returns>
        //object TryFindResource ( object resourceKey ) ;
    }
}