// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2213:'LeafService1' contains field '_svcReceiver' that is of IDisposable type 'ServiceHost', but it is never disposed. Change the Dispose method on 'LeafService1' to call Close or Dispose on this field.", Justification = "<Pending>", Scope = "member", Target = "~F:LeafService.LeafService1._svcReceiver")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter hostControl of method Continue is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:LeafService.LeafService1.Continue(Topshelf.HostControl)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter hostControl of method Pause is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:LeafService.LeafService1.Pause(Topshelf.HostControl)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter hostControl of method Shutdown is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:LeafService.LeafService1.Shutdown(Topshelf.HostControl)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member Shutdown does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:LeafService.LeafService1.Shutdown(Topshelf.HostControl)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter hostControl of method Start is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:LeafService.LeafService1.Start(Topshelf.HostControl)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'bool LeafService1.Start(HostControl hostControl)' passes a literal string as parameter 'message' of a call to 'void Logger.Debug(string message, string argument)'. Retrieve the following string(s) from a resource table instead: \"Existing service target endpoing is {endpoingAddress}\".", Justification = "<Pending>", Scope = "member", Target = "~M:LeafService.LeafService1.Start(Topshelf.HostControl)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'Logger.Debug(string, string)' could vary based on the current user's locale settings. Replace this call in 'LeafService1.Start(HostControl)' with a call to 'Logger.Debug(IFormatProvider, string, string)'.", Justification = "<Pending>", Scope = "member", Target = "~M:LeafService.LeafService1.Start(Topshelf.HostControl)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter hostControl of method Stop is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:LeafService.LeafService1.Stop(Topshelf.HostControl)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member Stop does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:LeafService.LeafService1.Stop(Topshelf.HostControl)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'string.ToString()' could vary based on the current user's locale settings. Replace this call in 'LogReceiver.ProcessLogMessages(NLogEvents)' with a call to 'string.ToString(IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:LeafService.LogReceiver.ProcessLogMessages(NLog.LogReceiverService.NLogEvents)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1812:LeafService1 is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "<Pending>", Scope = "type", Target = "~T:LeafService.LeafService1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1812:LogReceiver is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "<Pending>", Scope = "type", Target = "~T:LeafService.LogReceiver")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "DV2002:Class 'LeafService1' is not mapped to any Dependency Validation diagram.", Justification = "<Pending>", Scope = "type", Target = "~T:LeafService.LeafService1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "DV2002:Class 'LeafServiceModule' is not mapped to any Dependency Validation diagram.", Justification = "<Pending>", Scope = "type", Target = "~T:LeafService.LeafServiceModule")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "DV2002:Class 'LeafServiceTraceFilter' is not mapped to any Dependency Validation diagram.", Justification = "<Pending>", Scope = "type", Target = "~T:LeafService.LeafServiceTraceFilter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "DV2002:Class 'LogReceiver' is not mapped to any Dependency Validation diagram.", Justification = "<Pending>", Scope = "type", Target = "~T:LeafService.LogReceiver")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "DV2002:Class 'Program' is not mapped to any Dependency Validation diagram.", Justification = "<Pending>", Scope = "type", Target = "~T:LeafService.Program")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Architecture", "DV2002:Unmapped types", Justification = "<Pending>", Scope = "type", Target = "~T:LeafService.AddInException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:LeafService.LeafService1.InitializeAddin")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:LeafService.LeafService1.InitializeAddin")]