#region header
// Kay McCormick (mccor)
// 
// FileFinder3
// WpfApp1Tests3
// XunitTarget.cs
// 
// 2020-01-22-9:21 AM
// 
// ---
#endregion

using JetBrains.Annotations ;
using KayMcCormick.Dev.Tracing ;
using NLog ;
using NLog.Targets ;
using Xunit.Abstractions ;

namespace KayMcCormick.Dev.TestLib.Logging
{
    /// <summary></summary>
    /// <seealso cref="NLog.Targets.TargetWithLayout" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for XunitTarget
    [ Target ( "Xunit" ) ]
    public class XunitTarget : TargetWithLayout
    {
        /// <summary>Initializes a new instance of the <see cref="XunitTarget" /> class.</summary>
        /// <param name="name">The name.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public XunitTarget ( [ CanBeNull ] string name = null )
        {
            if ( name != null )
            {
                Name = name ;
            }
        }

        /// <summary>Gets or sets the output helper.</summary>
        /// <value>The output helper.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for OutputHelper
        public ITestOutputHelper OutputHelper { get ; set ; }


        /// <summary>
        ///     Writes logging event to the log target. Must be overridden in inheriting
        ///     classes.
        /// </summary>
        /// <param name="logEvent">Logging event to be written out.</param>
        protected override void Write ( LogEventInfo logEvent )
        {
            var logMessage = RenderLogEvent ( Layout , logEvent ) ;

            OutputHelper.WriteLine ( logMessage ) ;
            PROVIDER_GUID.EventWriteEVENT_TEST_OUTPUT ( logMessage ) ;
        }
    }
}