// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2000:Call System.IDisposable.Dispose on object created by 'new LogReceiverServerClient(new WSDualHttpBinding(), new EndpointAddress(\"http://exomail-87976:8737/discovery/scenarios/logreceiver/\"))' before all references to it are out of scope.", Justification = "<Pending>", Scope = "member", Target = "~M:ConfigTest.Program.Main")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "DV2002:Class 'Program' is not mapped to any Dependency Validation diagram.", Justification = "<Pending>", Scope = "type", Target = "~T:ConfigTest.Program")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "DV2002:Interface 'ILogReceiverServer' is not mapped to any Dependency Validation diagram.", Justification = "<Pending>", Scope = "type", Target = "~T:ConfigTest.ServiceReference1.ILogReceiverServer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "DV2002:Interface 'ILogReceiverServerChannel' is not mapped to any Dependency Validation diagram.", Justification = "<Pending>", Scope = "type", Target = "~T:ConfigTest.ServiceReference1.ILogReceiverServerChannel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "DV2002:Class 'LogReceiverServerClient' is not mapped to any Dependency Validation diagram.", Justification = "<Pending>", Scope = "type", Target = "~T:ConfigTest.ServiceReference1.LogReceiverServerClient")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "DV2002:Class 'StringCollection' is not mapped to any Dependency Validation diagram.", Justification = "<Pending>", Scope = "type", Target = "~T:ConfigTest.ServiceReference1.StringCollection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "DV2002:Class 'Test1' is not mapped to any Dependency Validation diagram.", Justification = "<Pending>", Scope = "type", Target = "~T:ConfigTest.Test1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "DV2002:Class 'Test2' is not mapped to any Dependency Validation diagram.", Justification = "<Pending>", Scope = "type", Target = "~T:ConfigTest.Test2")]