using System ;
using System.Collections ;
using System.Collections.ObjectModel ;
using System.Windows ;
using System.Windows.Controls ;
using System.Windows.Input ;
using System.Windows.Navigation ;
using Autofac ;
using KayMcCormick.Lib.Wpf ;
using NLog ;
using WpfApp.Application ;
using WpfApp.Controls ;

namespace WpfApp
{
    /// <summary>
    ///     Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : AppWindow
    {
        // ReSharper disable once InconsistentNaming
        // ReSharper disable once FieldCanBeMadeReadOnly.Local
        // ReSharper disable once InternalOrPrivateMemberNotDocumented
        private static Logger Logger = LogManager.GetCurrentClassLogger ( ) ;

       
        public MainWindow ( )
        {
            InitializeComponent ( ) ;

            try
            {
                if ( TryFindResource ( "ResolveServices" ) is ResolveServiceList resolveServiceList
                )
                {
                    foreach ( var resolveService in resolveServiceList )
                    {
                        var valueSource = DependencyPropertyHelper.GetValueSource (
                                                                                   resolveService
                                                                                 , AttachedProperties
                                                                                      .LifetimeScopeProperty
                                                                                  ) ;
                        var lifetimeScope = AttachedProperties.GetLifetimeScope ( resolveService ) ;
                        Logger.Warn (
                                     $"{resolveService.ServiceType} {lifetimeScope} {valueSource}"
                                    ) ;
                    }
                }
            }
            catch ( Exception )
            {
                // ignored
            }
        }

        public MainWindow ( ILifetimeScope lifetimeScope ) : base ( lifetimeScope )

        {
            InitializeComponent();

            try
            {
                if (TryFindResource("ResolveServices") is ResolveServiceList resolveServiceList
                )
                {
                    foreach (var resolveService in resolveServiceList)
                    {
                        var valueSource = DependencyPropertyHelper.GetValueSource(
                                                                                  resolveService
                                                                                , AttachedProperties
                                                                                     .LifetimeScopeProperty
                                                                                 );
                        Logger.Warn(
                                    $"{resolveService.ServiceType} {lifetimeScope} {valueSource}"
                                   );
                    }
                }
            }
            catch (Exception)
            {
                // ignored
            }

        }

        // ReSharper disable once ReturnTypeCanBeEnumerable.Global
        public ObservableCollection < ResourceNodeInfo > AllResources { get ; } =
            new ObservableCollection < ResourceNodeInfo > ( ) ;


        /// <summary>Gets the type frame.</summary>
        /// <value>The type frame.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for TypeFrame
        // ReSharper disable once UnusedMember.Global
        // public object TypeFrame => frame ;

        // ReSharper disable once InternalOrPrivateMemberNotDocumented
        private void Frame_OnNavigationFailed ( object sender , NavigationFailedEventArgs e )
        {
            var msg = $"{e.Exception.Message}; {e.ExtraData}" ;
            Logger.Error ( $"Nav failed: {msg}" ) ;
        }

        // ReSharper disable once InternalOrPrivateMemberNotDocumented
        private void Frame_OnNavigating ( object sender , NavigatingCancelEventArgs e )
        {
            Logger.Info ( e.ContentStateToSave ) ;
        }

        // ReSharper disable once InternalOrPrivateMemberNotDocumented
        private void VisitType ( object sender , ExecutedRoutedEventArgs e )
        {
            var eParameter = e.Parameter as Type ;
            if ( eParameter != null )
            {
                var typeControl2 = new TypeControl2 ( ) ;
                typeControl2.SetValue ( Props.RenderedTypeProperty , eParameter ) ;
                var findName = FindName ( "frame" ) as Frame ;
                findName?.Navigate ( typeControl2 ) ;
            }
        }


        private void Registrations_Loaded ( object sender , RoutedEventArgs e ) { }

        private void MainWindow_OnLoaded ( object sender , RoutedEventArgs e )
        {
        }


    }
}