// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:WpfApp2.PropertyCellTemplateSelector.Property")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'void DictInterceptor.Intercept(IInvocation invocation)', validate parameter 'invocation' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.DictInterceptor.Intercept(Castle.DynamicProxy.IInvocation)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'void DictInterceptor.Intercept(IInvocation invocation)' passes a literal string as parameter 'message' of a call to 'void Logger.Debug(string message, string argument)'. Retrieve the following string(s) from a resource table instead: \"{methodName}\".", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.DictInterceptor.Intercept(Castle.DynamicProxy.IInvocation)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'Logger.Debug(string, string)' could vary based on the current user's locale settings. Replace this call in 'DictInterceptor.Intercept(IInvocation)' with a call to 'Logger.Debug(IFormatProvider, string, string)'.", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.DictInterceptor.Intercept(Castle.DynamicProxy.IInvocation)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'LogProperty.LogProperty(string name, string header, string description, Type expectedType, string cellTemplateKey = null)', validate parameter 'expectedType' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.LogProperty.#ctor(System.String,System.String,System.String,System.Type,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'Logger.Info(string, int)' could vary based on the current user's locale settings. Replace this call in 'MainWindow.MainWindow()' with a call to 'Logger.Info(IFormatProvider, string, int)'.", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.MainWindow.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'MainWindow.MainWindow()' passes a literal string as parameter 'message' of a call to 'void Logger.Info(string message, int argument)'. Retrieve the following string(s) from a resource table instead: \"Number of props {numProps}\".", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.MainWindow.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.MainWindow.LoadLogFileAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'Logger.Debug(string, string)' could vary based on the current user's locale settings. Replace this call in 'MainWindow.LoadLogFileAsync()' with a call to 'Logger.Debug(IFormatProvider, string, string)'.", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.MainWindow.LoadLogFileAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.MainWindow.LoadLogFileButton_OnClick(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.MainWindow.OnLogLoadedAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'OnLogLoadedAsync' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.MainWindow.OnLogLoadedAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'SelectTemplate' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.PropertyCellTemplateSelector.SelectTemplate(System.Object,System.Windows.DependencyObject)~System.Windows.DataTemplate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'PropInfo.PropInfo(LogProperty logProperty)', validate parameter 'logProperty' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.PropInfo.#ctor(WpfApp2.LogProperty)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA3075:Unsafe overload of 'LoadXml' method", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.TemplateInfo.#ctor(System.Object,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA3075:An XmlDocument instance is created without setting its XmlResolver property to a secure value.", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.TemplateInfo.#ctor(System.Object,System.Windows.DataTemplate)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA3075:Unsafe overload of 'LoadXml' method", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.TemplatesWindow.CommandBinding_OnExecuted(System.Object,System.Windows.Input.ExecutedRoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'UIElement_OnLayoutUpdated' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:WpfApp2.TemplatesWindow.UIElement_OnLayoutUpdated(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'DateTime.Parse(string)' could vary based on the current user's locale settings. Replace this call in 'LogEntry.LoggedTime.get' with a call to 'DateTime.Parse(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~P:WpfApp2.LogEntry.LoggedTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'AllProps' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:WpfApp2.MainWindow.AllProps")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA3075:Unsafe overload of 'LoadXml' method", Justification = "<Pending>", Scope = "member", Target = "~P:WpfApp2.TemplateInfo.Template")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA3075:Unsafe overload of 'LoadXml' method", Justification = "<Pending>", Scope = "member", Target = "~P:WpfApp2.TemplateInfo.TemplateXaml")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1710:Rename WpfApp2.LogEntry to end in 'Dictionary'.", Justification = "<Pending>", Scope = "type", Target = "~T:WpfApp2.LogEntry")]