#region header
// Kay McCormick (mccor)
// 
// ConfigTest
// KayMcCormick.Dev
// AppLoggingConfiguration.cs
// 
// 2020-03-09-7:59 PM
// 
// ---
#endregion
using JetBrains.Annotations;
using NLog ;

namespace KayMcCormick.Dev.Logging
{
    /// <summary>
    /// 
    /// </summary>
    [UsedImplicitly]
    public class AppLoggingConfiguration : ILoggingConfiguration
    {
        private static readonly ILoggingConfiguration _default =
            new AppLoggingConfiguration { IsEnabledConsoleTarget = false , MinLogLevel = LogLevel.Info, IsEnabledDebuggerTarget = true } ;

        private bool? _isEnabledEventLogTarget = false ;
#pragma warning disable 649
        private bool? _isEnabledCacheTarget ;
#pragma warning restore 649
        private LogLevel _minLogLevel ;
        private string _debuggerTargetName ;
        private int ? _nLogViewerPort ;
        private int ? _chainsawPort ;
        private bool ? _isEnabledDebuggerTarget ;

        #region Implementation of ILoggingConfiguration
        /// <summary>
        /// 
        /// </summary>
        public bool? IsEnabledConsoleTarget { get; set; } 

        /// <summary>
        /// 
        /// </summary>
        public bool? IsEnabledEventLogTarget { get => _isEnabledEventLogTarget ;
            set => _isEnabledEventLogTarget = value ;
        }

        /// <summary>
        /// 
        /// </summary>
        public bool? IsEnabledCacheTarget => _isEnabledCacheTarget;

        /// <summary>Gets or sets the is enabled debugger target.</summary>
        /// <value>The is enabled debugger target.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for IsEnabledDebuggerTarget
        public bool ? IsEnabledDebuggerTarget
        {
            get => _isEnabledDebuggerTarget ;
            set => _isEnabledDebuggerTarget = value ;
        }

        /// <summary>
        /// 
        /// </summary>
        public string DebuggerTargetName => _debuggerTargetName ;

        /// <summary>
        /// 
        /// </summary>
        public int ? NLogViewerPort { get => _nLogViewerPort ; set => _nLogViewerPort = value ; }

        /// <summary>
        /// 
        /// </summary>
        public int? ChainsawPort { get => _chainsawPort ; set => _chainsawPort = value ; }

        /// <summary>
        /// 
        /// </summary>
        public LogLevel MinLogLevel { get => _minLogLevel ; set => _minLogLevel = value ; }

        /// <summary>
        /// 
        /// </summary>
        public static ILoggingConfiguration Default => _default ;
        #endregion

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public override string ToString ( )
        {
            return $"{nameof ( IsEnabledConsoleTarget )}: {IsEnabledConsoleTarget}, {nameof ( IsEnabledEventLogTarget )}: {IsEnabledEventLogTarget}, {nameof ( IsEnabledCacheTarget )}: {IsEnabledCacheTarget}, {nameof ( IsEnabledDebuggerTarget )}: {IsEnabledDebuggerTarget}, {nameof ( DebuggerTargetName )}: {DebuggerTargetName}, {nameof ( NLogViewerPort )}: {NLogViewerPort}, {nameof ( ChainsawPort )}: {ChainsawPort}, {nameof ( MinLogLevel )}: {MinLogLevel}" ;
        }
    }
}