namespace KayMcCormick.Dev.Logging
{
    /// <summary></summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for LogDelegates
    public static class LogDelegates
    {
        // public delegate void LogMethod (
        // string                      message
        // , [ CallerFilePath ]   string callerFilePath   = ""
        // , [ CallerMemberName ] string callerMemberName = ""
        // ) ;
        /// <summary></summary>
        /// <param name="message">The message.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for LogMethod
        public delegate void LogMethod ( string message ) ;
    }
}