#region header
// Kay McCormick (mccor)
// 
// Proj
// KayMcCormick.Dev
// MyCacheTarget2.cs
// 
// 2020-03-06-1:40 AM
// 
// ---
#endregion
using System ;
using System.Reactive.Linq ;
using System.Reactive.Subjects ;
using JetBrains.Annotations ;
using KmDevLib;
using NLog ;
using NLog.Config ;
using NLog.Targets ;

namespace KayMcCormick.Dev.Logging
{
    /// <summary></summary>
    /// <seealso cref="NLog.Targets.Target" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for MyCacheTarget
    [ Target ( nameof ( MyCacheTarget2 ) ) ]
    public class MyCacheTarget2 : TargetWithLayout
    {
        private readonly MyReplaySubject<string> _my1;
        // ##############################################################################################################################
        // Constructor
        // ##############################################################################################################################


        /// <summary>
        ///     Initializes a new instance of the <see cref="MyCacheTarget2" />
        ///     class.
        /// </summary>
        /// <param name="my1"></param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public MyCacheTarget2(MyReplaySubject<string> my1)
        {
            _my1 = my1;

            _cacheSubject = my1.Subject1;
        }


        /// <summary>
        ///     Writes logging event to the log target. Must be overridden in inheriting
        ///     classes.
        /// </summary>
        /// <param name="logEvent">Logging event to be written out.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Write
        protected override void Write ( LogEventInfo logEvent )
        {
            var rendered = RenderLogEvent ( Layout , logEvent ) ;
            _cacheSubject.OnNext ( rendered ) ;
        }


        // ##############################################################################################################################
        // Properties
        // ##############################################################################################################################

        // ##########################################################################################
        // Public Properties
        // ##########################################################################################

        /// <summary>
        ///     The maximum amount of entries held
        /// </summary>
        [ RequiredParameter ]
        public int MaxCount { get ; set ; } = 1000 ;

        /// <summary>Gets the cache.</summary>
        /// <value>The cache.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Cache

        [ JetBrains.Annotations.NotNull ] public IObservable < string > Cache
        {
            get { return _cacheSubject.AsObservable ( ) ; }
        }

        private readonly ReplaySubject < string > _cacheSubject ;     


        // ##########################################################################################
        // Private Properties
        // ##########################################################################################
    }
}