//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
[System.Xml.Serialization.XmlRootAttribute("Event", Namespace="http://schemas.microsoft.com/win/2004/08/events/event", IsNullable=false)]
public partial class EventType {
    
    private SystemPropertiesType systemField;
    
    private object itemField;
    
    private RenderingInfoType renderingInfoField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public SystemPropertiesType System {
        get {
            return this.systemField;
        }
        set {
            this.systemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BinaryEventData", typeof(byte[]), DataType="hexBinary")]
    [System.Xml.Serialization.XmlElementAttribute("DebugData", typeof(DebugDataType))]
    [System.Xml.Serialization.XmlElementAttribute("EventData", typeof(EventDataType))]
    [System.Xml.Serialization.XmlElementAttribute("ProcessingErrorData", typeof(ProcessingErrorDataType))]
    [System.Xml.Serialization.XmlElementAttribute("UserData", typeof(UserDataType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    public RenderingInfoType RenderingInfo {
        get {
            return this.renderingInfoField;
        }
        set {
            this.renderingInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class SystemPropertiesType {
    
    private SystemPropertiesTypeProvider providerField;
    
    private SystemPropertiesTypeEventID eventIDField;
    
    private byte versionField;
    
    private bool versionFieldSpecified;
    
    private byte levelField;
    
    private bool levelFieldSpecified;
    
    private ushort taskField;
    
    private bool taskFieldSpecified;
    
    private byte opcodeField;
    
    private bool opcodeFieldSpecified;
    
    private string keywordsField;
    
    private SystemPropertiesTypeTimeCreated timeCreatedField;
    
    private SystemPropertiesTypeEventRecordID eventRecordIDField;
    
    private SystemPropertiesTypeCorrelation correlationField;
    
    private SystemPropertiesTypeExecution executionField;
    
    private string channelField;
    
    private string computerField;
    
    private SystemPropertiesTypeSecurity securityField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public SystemPropertiesTypeProvider Provider {
        get {
            return this.providerField;
        }
        set {
            this.providerField = value;
        }
    }
    
    /// <remarks/>
    public SystemPropertiesTypeEventID EventID {
        get {
            return this.eventIDField;
        }
        set {
            this.eventIDField = value;
        }
    }
    
    /// <remarks/>
    public byte Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VersionSpecified {
        get {
            return this.versionFieldSpecified;
        }
        set {
            this.versionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte Level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LevelSpecified {
        get {
            return this.levelFieldSpecified;
        }
        set {
            this.levelFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ushort Task {
        get {
            return this.taskField;
        }
        set {
            this.taskField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaskSpecified {
        get {
            return this.taskFieldSpecified;
        }
        set {
            this.taskFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte Opcode {
        get {
            return this.opcodeField;
        }
        set {
            this.opcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OpcodeSpecified {
        get {
            return this.opcodeFieldSpecified;
        }
        set {
            this.opcodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Keywords {
        get {
            return this.keywordsField;
        }
        set {
            this.keywordsField = value;
        }
    }
    
    /// <remarks/>
    public SystemPropertiesTypeTimeCreated TimeCreated {
        get {
            return this.timeCreatedField;
        }
        set {
            this.timeCreatedField = value;
        }
    }
    
    /// <remarks/>
    public SystemPropertiesTypeEventRecordID EventRecordID {
        get {
            return this.eventRecordIDField;
        }
        set {
            this.eventRecordIDField = value;
        }
    }
    
    /// <remarks/>
    public SystemPropertiesTypeCorrelation Correlation {
        get {
            return this.correlationField;
        }
        set {
            this.correlationField = value;
        }
    }
    
    /// <remarks/>
    public SystemPropertiesTypeExecution Execution {
        get {
            return this.executionField;
        }
        set {
            this.executionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string Channel {
        get {
            return this.channelField;
        }
        set {
            this.channelField = value;
        }
    }
    
    /// <remarks/>
    public string Computer {
        get {
            return this.computerField;
        }
        set {
            this.computerField = value;
        }
    }
    
    /// <remarks/>
    public SystemPropertiesTypeSecurity Security {
        get {
            return this.securityField;
        }
        set {
            this.securityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class SystemPropertiesTypeProvider {
    
    private string nameField;
    
    private string guidField;
    
    private string eventSourceNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Guid {
        get {
            return this.guidField;
        }
        set {
            this.guidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EventSourceName {
        get {
            return this.eventSourceNameField;
        }
        set {
            this.eventSourceNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class RenderingInfoType {
    
    private string messageField;
    
    private string levelField;
    
    private string opcodeField;
    
    private string taskField;
    
    private string channelField;
    
    private string providerField;
    
    private string[] keywordsField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string cultureField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public string Level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    public string Opcode {
        get {
            return this.opcodeField;
        }
        set {
            this.opcodeField = value;
        }
    }
    
    /// <remarks/>
    public string Task {
        get {
            return this.taskField;
        }
        set {
            this.taskField = value;
        }
    }
    
    /// <remarks/>
    public string Channel {
        get {
            return this.channelField;
        }
        set {
            this.channelField = value;
        }
    }
    
    /// <remarks/>
    public string Provider {
        get {
            return this.providerField;
        }
        set {
            this.providerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Keyword", IsNullable=false)]
    public string[] Keywords {
        get {
            return this.keywordsField;
        }
        set {
            this.keywordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
    public string Culture {
        get {
            return this.cultureField;
        }
        set {
            this.cultureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class ProcessingErrorDataType {
    
    private uint errorCodeField;
    
    private string dataItemNameField;
    
    private byte[] eventPayloadField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public uint ErrorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    public string DataItemName {
        get {
            return this.dataItemNameField;
        }
        set {
            this.dataItemNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
    public byte[] EventPayload {
        get {
            return this.eventPayloadField;
        }
        set {
            this.eventPayloadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class DebugDataType {
    
    private uint sequenceNumberField;
    
    private bool sequenceNumberFieldSpecified;
    
    private string flagsNameField;
    
    private string levelNameField;
    
    private string componentField;
    
    private string subComponentField;
    
    private string fileLineField;
    
    private string functionField;
    
    private string messageField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public uint SequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SequenceNumberSpecified {
        get {
            return this.sequenceNumberFieldSpecified;
        }
        set {
            this.sequenceNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string FlagsName {
        get {
            return this.flagsNameField;
        }
        set {
            this.flagsNameField = value;
        }
    }
    
    /// <remarks/>
    public string LevelName {
        get {
            return this.levelNameField;
        }
        set {
            this.levelNameField = value;
        }
    }
    
    /// <remarks/>
    public string Component {
        get {
            return this.componentField;
        }
        set {
            this.componentField = value;
        }
    }
    
    /// <remarks/>
    public string SubComponent {
        get {
            return this.subComponentField;
        }
        set {
            this.subComponentField = value;
        }
    }
    
    /// <remarks/>
    public string FileLine {
        get {
            return this.fileLineField;
        }
        set {
            this.fileLineField = value;
        }
    }
    
    /// <remarks/>
    public string Function {
        get {
            return this.functionField;
        }
        set {
            this.functionField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class UserDataType {
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class ComplexDataType {
    
    private DataType[] dataField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public DataType[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class DataType {
    
    private string nameField;
    
    private System.Xml.XmlQualifiedName typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class EventDataType {
    
    private object[] itemsField;
    
    private byte[] binaryField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ComplexData", typeof(ComplexDataType))]
    [System.Xml.Serialization.XmlElementAttribute("Data", typeof(DataType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
    public byte[] Binary {
        get {
            return this.binaryField;
        }
        set {
            this.binaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class SystemPropertiesTypeEventID {
    
    private ushort qualifiersField;
    
    private bool qualifiersFieldSpecified;
    
    private ushort valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Qualifiers {
        get {
            return this.qualifiersField;
        }
        set {
            this.qualifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QualifiersSpecified {
        get {
            return this.qualifiersFieldSpecified;
        }
        set {
            this.qualifiersFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public ushort Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class SystemPropertiesTypeTimeCreated {
    
    private System.DateTime systemTimeField;
    
    private bool systemTimeFieldSpecified;
    
    private ulong rawTimeField;
    
    private bool rawTimeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime SystemTime {
        get {
            return this.systemTimeField;
        }
        set {
            this.systemTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SystemTimeSpecified {
        get {
            return this.systemTimeFieldSpecified;
        }
        set {
            this.systemTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong RawTime {
        get {
            return this.rawTimeField;
        }
        set {
            this.rawTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RawTimeSpecified {
        get {
            return this.rawTimeFieldSpecified;
        }
        set {
            this.rawTimeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class SystemPropertiesTypeEventRecordID {
    
    private ulong valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public ulong Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class SystemPropertiesTypeCorrelation {
    
    private string activityIDField;
    
    private string relatedActivityIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ActivityID {
        get {
            return this.activityIDField;
        }
        set {
            this.activityIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RelatedActivityID {
        get {
            return this.relatedActivityIDField;
        }
        set {
            this.relatedActivityIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class SystemPropertiesTypeExecution {
    
    private uint processIDField;
    
    private uint threadIDField;
    
    private byte processorIDField;
    
    private bool processorIDFieldSpecified;
    
    private uint sessionIDField;
    
    private bool sessionIDFieldSpecified;
    
    private uint kernelTimeField;
    
    private bool kernelTimeFieldSpecified;
    
    private uint userTimeField;
    
    private bool userTimeFieldSpecified;
    
    private uint processorTimeField;
    
    private bool processorTimeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint ProcessID {
        get {
            return this.processIDField;
        }
        set {
            this.processIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint ThreadID {
        get {
            return this.threadIDField;
        }
        set {
            this.threadIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte ProcessorID {
        get {
            return this.processorIDField;
        }
        set {
            this.processorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ProcessorIDSpecified {
        get {
            return this.processorIDFieldSpecified;
        }
        set {
            this.processorIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint SessionID {
        get {
            return this.sessionIDField;
        }
        set {
            this.sessionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SessionIDSpecified {
        get {
            return this.sessionIDFieldSpecified;
        }
        set {
            this.sessionIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint KernelTime {
        get {
            return this.kernelTimeField;
        }
        set {
            this.kernelTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool KernelTimeSpecified {
        get {
            return this.kernelTimeFieldSpecified;
        }
        set {
            this.kernelTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint UserTime {
        get {
            return this.userTimeField;
        }
        set {
            this.userTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UserTimeSpecified {
        get {
            return this.userTimeFieldSpecified;
        }
        set {
            this.userTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint ProcessorTime {
        get {
            return this.processorTimeField;
        }
        set {
            this.processorTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ProcessorTimeSpecified {
        get {
            return this.processorTimeFieldSpecified;
        }
        set {
            this.processorTimeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/win/2004/08/events/event")]
public partial class SystemPropertiesTypeSecurity {
    
    private string userIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UserID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
}
