#region header
// Kay McCormick (mccor)
// 
// WpfApp2
// CodeAnalysisApp1
// Ext.cs
// 
// 2020-02-14-1:05 AM
// 
// ---
#endregion
using System.Collections.Generic ;
using Microsoft.CodeAnalysis ;

namespace CodeAnalysisApp1
{
    /// <summary>Extension class</summary>
    public static class Ext
    {
        // public static implicit operator IEnumerable < ITypeSymbol ? > ( this TypeInfo me )
        //     => new[] { me.Type , me.ConvertedType } ;
        /// <summary>Types the infos.</summary>
        /// <param name="me">Me.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for TypeInfos
        public static IEnumerable < ITypeSymbol > TypeInfos ( this TypeInfo me )
        {
            return new[] { me.Type , me.ConvertedType } ;
        }

        /// <summary>Deconstructs the specified type1.</summary>
        /// <param name="me">Me.</param>
        /// <param name="type1">The type1.</param>
        /// <param name="type2">The type2.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Deconstruct
        // ReSharper disable once UnusedMember.Global
        public static void Deconstruct (
            this TypeInfo    me
          , out  ITypeSymbol  type1
          , out  ITypeSymbol  type2
        )
        {
            type1 = me.Type ;
            type2 = me.ConvertedType ;
        }
    }
}