// <auto-generated />
using System;
using ConsoleAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleAnalysis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200417172338_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnalysisAppLib.Syntax.AppMethodInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppTypeInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppTypeInfoId");

                    b.ToTable("AppMethodInfo");
                });

            modelBuilder.Entity("AnalysisAppLib.Syntax.AppParameterInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppMethodInfoId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppMethodInfoId");

                    b.ToTable("AppParameterInfo");
                });

            modelBuilder.Entity("AnalysisAppLib.Syntax.AppTypeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ColorValue")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ElementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("int");

                    b.Property<int?>("ParentInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentInfoId");

                    b.ToTable("AppTypeInfos");
                });

            modelBuilder.Entity("AnalysisAppLib.Syntax.AppMethodInfo", b =>
                {
                    b.HasOne("AnalysisAppLib.Syntax.AppTypeInfo", null)
                        .WithMany("FactoryMethods")
                        .HasForeignKey("AppTypeInfoId");
                });

            modelBuilder.Entity("AnalysisAppLib.Syntax.AppParameterInfo", b =>
                {
                    b.HasOne("AnalysisAppLib.Syntax.AppMethodInfo", null)
                        .WithMany("Parameters")
                        .HasForeignKey("AppMethodInfoId");
                });

            modelBuilder.Entity("AnalysisAppLib.Syntax.AppTypeInfo", b =>
                {
                    b.HasOne("AnalysisAppLib.Syntax.AppTypeInfo", "ParentInfo")
                        .WithMany("SubTypeInfos")
                        .HasForeignKey("ParentInfoId");
                });
#pragma warning restore 612, 618
        }
    }
}
